<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluxzy.Core" Version="1.34.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JiuMi.Domain\JiuMi.Domain.csproj" />
  </ItemGroup>

</Project>
