<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Assets\I18n\en-US.axaml" />
    <AvaloniaXaml Remove="Assets\I18n\zh-CN.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.10" />
    <PackageReference Include="FluentAvaloniaUI" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JiuMi.Application\JiuMi.Application.csproj" />
    <ProjectReference Include="..\JiuMi.Infrastructure\JiuMi.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\I18n\en-US.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\I18n\Keys.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Keys.cs</LastGenOutput>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\I18n\Keys.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Keys.tt</DependentUpon>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\I18n\zh-CN.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Assets\I18n\Keys.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Keys.tt</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
